setup capybara
shahzaman900/blog-rails pull request #9
Opened 2023-11-17 09:52 UTC by sheezu900

2023-11-17 14:52 UTC, Whoistolu requested changes
Hi @sheezu900 , @Graciano1997 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [x]  _Check the inline comments under the review for sections to improve._
- [x] NB: I am adding this recommendation here because they are not present in the file changes

- [ ] [REQUIRED] There are some test missing for the featured tests for `User` show page
- Tests that redirects to the post's show page when you click on a user's post.
- Tests that redirects to the user's post's index page when you click on a **see all posts**.

- [ ] [REQUIRED] There are some test missing in the featured tests for `User` **post index page**
- Kindly add tests that asserts you can see a post's title.
- Tests that asserts you can see the first comments on a post.
- Tests that redirects to the post's show page when you click on a post.

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-17 14:52 UTC, Whoistolu commented on spec/features/post_show_spec.rb
>      6.times { Like.create(post: @fu.posts.first, user: @fu) }
- [ ] [REQUIRED] Kindly add a test that asserts you can see the username of each commentor.
- [ ] [REQUIRED] Kindly add tests that asserts you can see the comment each commentor left.
This hard requirements,let's fix this team.

2023-11-17 14:52 UTC, Whoistolu commented on app/views/posts/index.html.erb
> +    <%# <% end %>
- [ ] [OPTIONAL] Kindly remove all unused comments

2023-11-17 20:13 UTC, Gambit142 requested changes
Hi @sheezu900 @Graciano1997 👋, 

#### Great work on making the changes requested by a previous reviewer and fixing the error that made most tests not pass 👏 

### Highlights
- Setup linters correctly ✔️ 
- Use of Rsec testing library ✔️ 
- Wrote feature spec tests ✔️

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer and addressing them will improve your application._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-17 20:13 UTC, Gambit142 commented on spec/features/user_show_spec.rb
> +    end
- [x] There is a syntax error here and it is affecting the tests from running. Kindly remove one `end` statement here. 👍 😎

2023-11-17 20:13 UTC, Gambit142 commented on spec/features/post_show_spec.rb
>      Comment.delete_all
### Although I am highlighting this file, this suggested change should be done in the `spec/features/posts_index_spec.rb` file. 

- [ ] As highlighted by the previous reviewer, kindly do the following:

- Write a test that redirects to the `Posts#Show` page when you click on a post on the `Posts#Index` page. 

The code you wrote in the screenshot below in the `spec/features/posts_index_spec.rb` file is directing to the `Posts#Show` page from the `Users#Show` page and not the `Posts#Index` page. Kindly write the correct test 👍 :

![image](https://github.com/sheezu900/blog-rails/assets/77106962/f9537cf1-a951-40ee-92f8-4705655aae42)

2023-11-17 20:13 UTC, Gambit142 commented on spec/features/user_show_spec.rb
> +    end
- [ ] After you implemented some changes that the first reviewer suggested, I noticed that 30 tests out of 34 tests are failing. Kindly fix the tests and ensure that all tests pass after implementing all changes. 💻 😎 

![image](https://github.com/sheezu900/blog-rails/assets/77106962/0caaffb6-ec31-4955-85af-079d96c7a1a9)

2023-11-17 23:00 UTC, codepantha requested changes
# STATUS: CHANGES REQUIRED ♻️ 

## Hi team 👋, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media2.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif"/>

## Highlights 🎯 
- Setup linters correctly ✔️
- Use of Rsec testing library ✔️
- Wrote feature spec tests ✔️


## Suggested changes
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-11-17 23:00 UTC, codepantha commented on spec/features/user_show_spec.rb
> +encouraged
- [ ] This line here prevents the code from running correctly as can be seen in the attached image below 👇 
Kindly remove `encouraged` and replace it with `end` 👍 

![image](https://github.com/sheezu900/blog-rails/assets/46839548/3bd552ca-6a5e-425b-abdb-800fae3f58cd)

2023-11-18 01:19 UTC, Shedrack-Sunday approved these changes
Hi @sheezu900       👍 

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![image](https://github.com/krisbobo/blog-app/assets/50990925/76d09bb1-9dc7-46c0-be49-31f366afa4b8)


Highlights
- [x] Good project organization ✔️
- [x] Nice use of Rails  features  ✔️  
- [x] Kudus on meeting the requirements as pointed the last time out   👏 


Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-11-18 04:23 UTC, merged